spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          name: HelloService
        username: admin
        password: admin
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        # SpringBootActuator开启所有权限
        include: "*"


